# Generated by Django 4.1.5 on 2023-01-08 22:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pc', models.CharField(choices=[('PROVIDER', 'provider'), ('COSTUMER', 'customer'), ('BOTH', 'both')], max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('corporate_number', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
