# Generated by Django 4.1.5 on 2023-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
