# Generated by Django 4.1.5 on 2023-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='country',
            field=models.CharField(choices=[('UZBEKISTAN', 'uzbekistan'), ('KYRGIZISTAN', 'kyrgizistan'), ('KAZAKHSTAN', 'kazakhstan'), ('TURKMENISTAN', 'turkmenistan'), ('TADJIKISTAN', 'tadjikistan')], max_length=50),
        ),
    ]
