# Generated by Django 4.1.5 on 2023-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customeruser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
