# Generated by Django 4.1.5 on 2023-01-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
