# Generated by Django 4.1.5 on 2023-01-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
