# Generated by Django 4.1.5 on 2023-01-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
