# Generated by Django 4.1.5 on 2023-01-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_password_user_password1_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
    ]
