# Generated by Django 4.1.5 on 2023-01-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_password1_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
