# Generated by Django 4.1.5 on 2023-01-10 17:20

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pc', models.CharField(choices=[('PROVIDER', 'provider'), ('COSTUMER', 'customer'), ('BOTH', 'both')], max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('corporate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
