# Generated by Django 4.1.5 on 2023-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('UZBEKISTAN', 'uzbekistan'), ('KYRGIZISTAN', 'kyrgizistan'), ('KAZAKHSTAN', 'kazakhstan'), ('TURKMENISTAN', 'turkmenistan'), ('TADJIKISTAN', 'tadjikistan')], default='default country', max_length=50),
            preserve_default=False,
        ),
    ]
