# Generated by Django 4.1.5 on 2023-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
