# Generated by Django 4.1.5 on 2023-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default='default company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='trade_name_of_the_drug',
            field=models.CharField(default='default trade_name_of_the_drug', max_length=50),
            preserve_default=False,
        ),
    ]
