# Generated by Django 4.1.5 on 2023-02-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_company_product_trade_name_of_the_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(default='default active_ingredient', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='default composition', max_length=1000),
            preserve_default=False,
        ),
    ]
