# Generated by Django 4.1.5 on 2023-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_active_ingredient_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contraindication',
            field=models.TextField(default='default contraindication', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacotherapeutic_group',
            field=models.TextField(default='default pharmacotherapeutic_group', max_length=5000),
            preserve_default=False,
        ),
    ]
