# Generated by Django 4.1.5 on 2023-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_contraindication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pharmacokinetic',
            field=models.TextField(default='default pharmacokinetic', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(default='default storage_condition', max_length=500),
            preserve_default=False,
        ),
    ]
