# Generated by Django 4.1.5 on 2023-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_pharmacokinetic_product_storage_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration',
            field=models.CharField(default='default expiration', max_length=255),
            preserve_default=False,
        ),
    ]
