# Generated by Django 4.1.5 on 2023-02-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='user',
        ),
    ]
