# Generated by Django 4.1.5 on 2023-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
