# Generated by Django 4.1.5 on 2023-02-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetail_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
    ]
